# static ????? html(??? ???? ?? ?? ?)? ??
# templates ????? 

# server port number
server:
  port: 8086
  servlet:
    context-path: /pro07 # ??? ???? ?? ??? ?? ??

# spring boot, jsp (/src/main/webapp/WEB-INF/view)
#maria db set
spring:
  profiles:
    active: local # ?? ????
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/** # css, js, html ?? ??
    hidden-method:
      filter:
        enabled: true # PUT, DELETE ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tsherpa
    username: root
    password: 1234

#myBatis set
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.chunjae.test07.entity
  mapper-locations: mapppers/**/*.xml

# log
logging:
  config: classpath:logback.xml