CREATE DATABASE edumon;

USE edumon;

CREATE TABLE userinfo (
	NO INT PRIMARY KEY AUTO_INCREMENT,
	id VARCHAR(20) NOT NULL,
	pw VARCHAR(200) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	email VARCHAR(100),
	tel VARCHAR(20),
	regdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	